// FETCH ZIPCODES ACTION NAMES
export const SERVER_ADDRESS = 'SERVER_ADDRESS';
export const FETCH_ZIPCODES = 'FETCH_ZIPCODES';
export const FETCH_ZIPCODES_PENDING = 'FETCH_ZIPCODES_PENDING';
export const FETCH_ZIPCODES_FULFILLED = 'FETCH_ZIPCODES_FULFILLED';
export const FETCH_ZIPCODES_REJECTED = 'FETCH_ZIPCODES_REJECTED';
export const TRY_LOGIN = 'TRY_LOGIN';