// FETCH ZIPCODES ACTION NAMES
export const SERVER_ADDRESS = '';
export const FETCH_ZIPCODES = 'FETCH_ZIPCODES';
export const FETCH_ZIPCODES_PENDING = 'FETCH_ZIPCODES_PENDING';
export const FETCH_ZIPCODES_FULFILLED = 'FETCH_ZIPCODES_FULFILLED';
export const FETCH_ZIPCODES_REJECTED = 'FETCH_ZIPCODES_REJECTED';
export const TRY_LOGIN = 'TRY_LOGIN';

/** Migrated Code Constants**/
export const SESSION_INFO="SESSION_INFO";
export const GET_STATE="GET_STATE";
export const GET_COMPANY_DETAIL="GET_COMPANY_DETAIL";
export const BREADCRUMB="BREADCRUMB";
export const ENTERPRISE_COMPANY="ENTERPRISE_COMPANY";
// ENTERPRISE_COMPANY

/* Temp */
export const CREATE_NEW_PASS = "CREATE_NEW_PASS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_DATA_RESET = "LOGIN_DATA_RESET"

//Filter Data Constants
export const GET_ENTERPRICE_LIST = "GET_ENTERPRICE_LIST";
export const GET_COMPANY_LIST = "GET_COMPANY_LIST";
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";

export const SELECTED_ENTERPRISE= "SELECTED_ENTERPRISE";
export const SELECTED_COMPANY = "SELECTED_COMPANY";
export const SELECTED_PROJECT = "SELECTED_PROJECT";
